config/routes.rb
FootballPredictions::Application.routes.draw do

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :predictions, :only => [:index, :new, :create]
  resources :fixtures, :only => [:index, :new, :create]
  resources :leagues, :only => [:new, :create]
  resources :results, :only => [:new, :create]
  resources :mini_leagues, :only => [:index, :new, :create]
  resources :teams, :only => [:index, :new, :create]
  resources :enrollments, :only => [:index, :new, :create]


  scope :controller => :predictions do
    get 'index'

  end
 

  scope :controller => :main do
    get 'index'
    get 'fixturelist'
    get 'leaguetable'
  end

  scope :controller => :members do
    get 'index'
  end

  # Directing the user after login
  authenticated :user do
    root :to => 'members#index'
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'main#index'


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  include LeagueGrabber::GetTable

	def index
    
	end

	def fixturelist
	  @fixtures = Fixture.all
	  @fixture_date = @fixtures.group_by {|fd| fd.fixture_date }

	end

  def leaguetable
    @league = League.all
  end
  
end

app/helpers/main_helper.rb
module MainHelper
end

app/views/main/fixturelist.html.erb
<%= link_to "Make Predictions", new_prediction_path %>
<h1>Fixture List</h1>

<% @fixture_date.sort.each do |date, fixtures| %>
  <h4><%= date_format(date) %></h4>

  <% fixtures.each do |fixture| %>
    <%= fixture.home_team %> VS <%= fixture.away_team %><br>
  <% end %>
<% end %>

app/views/main/index.html.erb
<div class="container">
  <div class="row">
    <div id="respLogin" class="span4 offset4 well">
     <legend>Sign In</legend>
        <div class="social">
          Sign in using Social Network<br>
            <div class="google">
              <%= ilink_to "google-plus-sign", "Sign in with Google + ", user_omniauth_authorize_path(:google_oauth2), :class => 'btn btn-danger' %>
            </div>
            <div class="fb">
             <%= ilink_to "facebook-sign", "Sign in with Facebook", user_omniauth_authorize_path(:facebook), :class => 'btn btn-blue' %>

            </div>  
          </div>

      <div id="login">
        Sign in with registered account:
       <%= form_for(resource, :as => resource_name, :html => {class:"form-horizontal"}, :url => session_path(resource_name))  do |f| %>
       <fieldset>
        <%= f.email_field :email, :autofocus => true, :class => 'login user', :placeholder => 'Username' %>
        <%= f.password_field :password, :class => 'login password', :placeholder => 'Password' %>
      
     </div><!--login-->

     <div class="button">
      <%= f.submit "Sign in", :class => 'btn btn-primary'  %>
    </div>

<div class="checkbox">
  <% if devise_mapping.rememberable? -%>
        <label class="choice">Keep me signed in
        <%= f.check_box :remember_me %>
        </label>
  <% end -%>
</div>
</fieldset>
<% end %>




    </div>
  </div>
</div>

app/views/main/leaguetable.html.erb
<div class="league-table-content">
  <table class="table-stats">
    <thead>
      <tr class="header">
        <th class="position">Pos</th>
        <th class="team-name">Team</th>
        <th class="played">P</th>
        <th class="goal-difference">GD</th>
        <th class="points">Pts</th>
      </tr>
    </thead>
    <tbody>
      <% @league.each do |l| %>
     <tr class="team">
      <td class="position"><%= l.position %></td>
      <td class="team-name"><%= l.team_name %></td>
      <td class="played"><%= l.played %></td> 
      <td class="goal-difference"><%= l.goal_difference %></td> 
      <td class="points"><%= l.points %></td> 
      <% end %>



     </tr>


    </tbody>

</table>
</div>