config/routes.rb
FootballPredictions::Application.routes.draw do

  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }

  resources :predictions, :only => [:index, :new, :create]
  resources :fixtures, :only => [:index, :new, :create]
  resources :leagues, :only => [:new, :create]
  resources :results, :only => [:new, :create]
  resources :mini_leagues, :only => [:index, :new, :create]
  resources :teams, :only => [:index, :new, :create]
  resources :enrollments, :only => [:index, :new, :create]


  scope :controller => :predictions do
    get 'index'

  end
 

  scope :controller => :main do
    get 'index'
    get 'fixturelist'
    get 'leaguetable'
  end

  scope :controller => :members do
    get 'index'
  end

  # Directing the user after login
  authenticated :user do
    root :to => 'members#index'
  end

  # You can have the root of your site routed with "root"
  # just remember to delete public/index.html.
  root :to => 'main#index'


  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
end

app/views/shared/_navbar.html.erb
<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="/">Premier Predictions</a>
       <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav pull-right">
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
       </div>
     </div>
   </div>
 </div>

app/views/shared/_usernavbar.html.erb
<div class="navbar navbar-fixed-top">
   <div class="navbar-inner">
     <div class="container">
       <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
         <span class="icon-bar"></span>
       </a>
       <a class="brand" href="../">Premier Predictions</a>
       <div class="nav-collapse collapse" id="main-menu">
        <ul class="nav pull-right">
          <li><%= link_to "#{current_user.name}", edit_user_registration_path %></li>
          <li><%= link_to "My Predicitons", predictions_path %></li>
          <li><%= login_status %></li>  
       </div>
     </div>
   </div>
 </div>